//! Push-to-talk dictation: hold a key, speak, release, and the transcript
//! lands in the prompt box.
//!
//! The recogniser is an external sidecar process (`sidecar.rs`) because audio
//! capture and ONNX inference cannot be linked into tcode without breaking
//! release targets that have neither — see this crate's `AGENTS.md`.
//! Everything in this module is therefore about *driving* a backend, never
//! about audio.
//!
//! Two rules the rest of the app depends on:
//! - A transcript only ever reaches the editor. Voice never submits.
//! - The gesture shown in the hint is the gesture that actually works on this
//!   terminal. What that is cannot be known in advance — see `EndDetect`, which
//!   is discovered from the terminal's own behaviour, one tier at a time.

mod sidecar;

use std::time::{Duration, Instant};

use tcode_core::config::{VoiceConfig, VoiceKey};
use tokio::sync::mpsc;

pub(crate) use sidecar::{install_path, list_models, release_asset, SidecarBackend, VoiceModel};

/// Shorter than this and the key was tapped, not held. Transcribing 80ms of
/// room tone wastes a second and returns nothing useful.
const MIN_HOLD: Duration = Duration::from_millis(200);

/// A release this soon after the press did not come from a finger. Nobody can
/// hold a key for under ~70ms, so this is a terminal manufacturing a release
/// for every press (see `EndDetect::Repeat`).
const SYNTHETIC_RELEASE: Duration = Duration::from_millis(60);

/// How long to wait for auto-repeat to begin before concluding the key was
/// tapped rather than held. It has to clear the OS repeat *delay*, which is
/// around 500ms by default on Windows.
const REPEAT_START: Duration = Duration::from_millis(700);

/// Floor for the "repeats have stopped, so the key is up" gap. Above the
/// steady-state repeat interval of any normal setting, and low enough that the
/// take does not visibly drag on after the finger lifts.
const REPEAT_GAP_MIN: Duration = Duration::from_millis(250);

/// Repeats needed to call a provisional take a hold, when the terminal will
/// not label auto-repeat itself.
///
/// Waiting is close to free — the microphone opened on the *first* press, so
/// only the visual confirmation is delayed, never the audio — while guessing
/// early costs the user the characters they were typing.
///
/// Two, i.e. three presses. One was observably not enough: typing two spaces
/// is something people do. What makes two safe rather than merely less wrong
/// is `FAST_REPEAT` below; raise this first if it still misfires.
const PROVISIONAL_REPEATS: u32 = 2;

/// And they have to arrive at machine speed. A held key repeats far faster
/// than anyone types the same key on purpose, which is the difference that
/// actually separates the two — the count alone would eventually be reached by
/// someone laying out spaces.
const FAST_REPEAT: Duration = Duration::from_millis(180);

/// How the end of a hold is recognised. Which one applies is discovered from
/// what the terminal actually does, never assumed — see `Voice::on_release`.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub(crate) enum EndDetect {
    /// The terminal reports a real key-up. Best case, and what the kitty
    /// protocol and win32-input-mode are requested for.
    Release,
    /// The terminal manufactures a release in the same instant as every press,
    /// so key-up carries no information. The key is held for as long as the
    /// OS keeps sending auto-repeat, and it is up once the repeats stop.
    ///
    /// This is what makes hold-to-talk work under a pseudoconsole at all:
    /// auto-repeat is generated by the OS keyboard layer and travels the VT
    /// stream like any other keystroke, while key-up does not survive it.
    Repeat,
    /// Neither a usable release nor auto-repeat. The key toggles instead.
    Toggle,
}

/// What the presses of one take looked like. Only meaningful while recording.
#[derive(Debug, Clone, Copy)]
struct PressTrack {
    last: Instant,
    /// Interval between the two most recent repeats — the steady-state repeat
    /// rate, which the *first* gap is not (that one is the repeat delay).
    gap: Option<Duration>,
    repeats: u32,
}

impl PressTrack {
    fn new() -> Self {
        Self {
            last: Instant::now(),
            gap: None,
            repeats: 0,
        }
    }

    fn note_repeat(&mut self) {
        let now = Instant::now();
        if self.repeats > 0 {
            self.gap = Some(now - self.last);
        }
        self.repeats += 1;
        self.last = now;
    }

    /// Silence longer than this means the key is up. Derived from the observed
    /// rate so a slow repeat setting does not cut takes short.
    fn idle_limit(&self) -> Duration {
        match self.gap {
            Some(gap) => (gap * 3).max(REPEAT_GAP_MIN),
            None => REPEAT_START,
        }
    }
}

/// What the backend tells us. Deliberately small: anything richer would be a
/// protocol the sidecar has to keep in sync for no gain.
#[derive(Debug, Clone, PartialEq)]
pub(crate) enum VoiceEvent {
    /// Model loaded, microphone open, commands will be honoured.
    Ready,
    /// Fetching the model, 0-100. Reported by the sidecar itself.
    Downloading(u8),
    /// Fetching the sidecar, 0-100. Reported by tcode, before there is a
    /// sidecar to report anything.
    Installing(u8),
    /// The sidecar is on disk. The app starts it on seeing this; `Voice` never
    /// sees the event, which is why it has no state of its own.
    Installed,
    /// Input level while recording, 0.0-1.0.
    Level(f32),
    Transcript(String),
    Failed(String),
}

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub(crate) enum VoiceCmd {
    Start,
    Stop,
    Cancel,
}

/// A running recogniser. One implementation ships (`SidecarBackend`); the
/// trait exists so tests can script one without audio hardware.
pub(crate) trait VoiceBackend: Send {
    fn send(&mut self, cmd: VoiceCmd) -> Result<(), String>;
}

#[allow(clippy::type_complexity)]
pub(crate) type BackendFactory = Box<
    dyn Fn(&VoiceConfig, mpsc::Sender<VoiceEvent>) -> Result<Box<dyn VoiceBackend>, String>
        + Send
        + Sync,
>;

#[derive(Debug, Clone, PartialEq)]
pub(crate) enum VoiceState {
    Off,
    /// Fetching the sidecar binary itself, before any of it can run.
    Installing(u8),
    /// Backend spawned but not usable yet; `Some` while a model downloads.
    Warming(Option<u8>),
    Ready,
    Recording {
        since: Instant,
        level: f32,
    },
    Transcribing,
    /// Turned on but unusable, holding the reason. Kept visible rather than
    /// silently falling back to Off: a mic that stopped working must not look
    /// like a feature the user forgot to enable.
    Unavailable(String),
}

/// What the app must do in response. Voice owns no App state, so anything
/// with an outside effect comes back through here.
#[derive(Debug, Clone, PartialEq)]
pub(crate) enum VoiceOutcome {
    None,
    /// Insert at the cursor. Never submitted.
    Insert(String),
    /// Transient, shown in the hint row until it fades.
    Notice(String),
    /// Something the user needs to still be able to read afterwards, so it
    /// goes into the transcript rather than a row that fades and truncates.
    Announce(String),
    /// Let the keystroke type its character as well: this take is provisional
    /// and the key may yet turn out to have been the user typing.
    TypeSpace,
    /// The hold is confirmed — take back every character typed on the way in.
    RetractSpaces(u32),
}

/// The two halves of the hint row: a coloured lead and dim detail.
pub(crate) struct VoiceHint {
    pub(crate) lead: String,
    pub(crate) rest: String,
    pub(crate) tone: HintTone,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub(crate) enum HintTone {
    /// Working on it — same accent as every other in-flight thing.
    Busy,
    /// The microphone is open. Red, because that is what red means here.
    Recording,
    Problem,
}

/// One key event, spelled the way `[voice] key` spells it. `/voice keys`
/// echoes these so that "the key does nothing" can be told apart from "the
/// key never arrived" — an input method that claims ctrl+space swallows it
/// before any terminal sees it, and nothing else on screen would show that.
pub(crate) fn describe_key(key: &crossterm::event::KeyEvent) -> String {
    use crossterm::event::{KeyCode, KeyEventKind, KeyModifiers};
    let mut parts: Vec<String> = Vec::new();
    for (flag, name) in [
        (KeyModifiers::CONTROL, "ctrl"),
        (KeyModifiers::ALT, "alt"),
        (KeyModifiers::SHIFT, "shift"),
    ] {
        if key.modifiers.contains(flag) {
            parts.push(name.into());
        }
    }
    parts.push(match key.code {
        KeyCode::Char(' ') => "space".into(),
        KeyCode::Char(c) => c.to_string(),
        KeyCode::F(n) => format!("f{n}"),
        other => format!("{other:?}").to_lowercase(),
    });
    let kind = match key.kind {
        KeyEventKind::Press => "press",
        KeyEventKind::Repeat => "repeat",
        KeyEventKind::Release => "release",
    };
    format!("{} · {kind}", parts.join("+"))
}

/// The first take begins with the universally observable repeat signal. A
/// non-synthetic release upgrades it to the lower-latency `Release` path.
/// This deliberately does not probe terminal capabilities: Crossterm's probe
/// sends a Device Attributes query whose delayed reply can leak into the shell
/// during teardown.
fn initial_end_detect() -> EndDetect {
    #[cfg(windows)]
    {
        EndDetect::Release
    }
    #[cfg(not(windows))]
    {
        EndDetect::Repeat
    }
}

pub(crate) struct Voice {
    cfg: VoiceConfig,
    state: VoiceState,
    backend: Option<Box<dyn VoiceBackend>>,
    factory: BackendFactory,
    events: mpsc::Sender<VoiceEvent>,
    /// Whether the key is down as far as we can tell. Only `Toggle` relies on
    /// it; the other two read the terminal's own signals.
    held: bool,
    end_detect: EndDetect,
    press: PressTrack,
    /// Takes that ended with no auto-repeat at all. Two in a row means this
    /// terminal offers neither signal and the gesture has to become a toggle.
    silent_takes: u32,
    /// This take might not be one: the key was `space`, which is also a
    /// character, so it was allowed to type itself and the recording stays
    /// hidden until the hold is confirmed. See `Voice::on_press`.
    provisional: bool,
    /// How many characters the provisional take has let through, and therefore
    /// how many to take back if it turns out to be a hold. Every press counts,
    /// not just the first: two spaces typed in a row must leave two spaces.
    provisional_chars: u32,
}

impl Voice {
    pub(crate) fn new(
        cfg: VoiceConfig,
        events: mpsc::Sender<VoiceEvent>,
        factory: BackendFactory,
    ) -> Self {
        Self {
            cfg,
            state: VoiceState::Off,
            backend: None,
            factory,
            events,
            held: false,
            end_detect: initial_end_detect(),
            press: PressTrack::new(),
            silent_takes: 0,
            provisional: false,
            provisional_chars: 0,
        }
    }

    /// Override the initial detection strategy. Tests pin this so terminal
    /// events on the machine running them are not part of what they check.
    #[cfg(test)]
    pub(crate) fn set_end_detect(&mut self, how: EndDetect) {
        self.end_detect = how;
    }

    /// Backdate the take in progress, so a test can be past `MIN_HOLD`
    /// without sleeping.
    #[cfg(test)]
    pub(crate) fn pretend_recording_started(&mut self, ago: Duration) {
        if let VoiceState::Recording { since, .. } = &mut self.state {
            *since = Instant::now() - ago;
        }
    }

    pub(crate) fn default_factory() -> BackendFactory {
        Box::new(|cfg, tx| {
            SidecarBackend::spawn(cfg, tx).map(|backend| Box::new(backend) as Box<dyn VoiceBackend>)
        })
    }

    /// Should voice come up with the session? `[voice] enabled`, already
    /// resolved against the runtime toggle in the selected config's
    /// `[tcode_state]` table.
    pub(crate) fn wants_on(&self) -> bool {
        self.cfg.enabled
    }

    pub(crate) fn is_on(&self) -> bool {
        !matches!(self.state, VoiceState::Off)
    }

    /// True while audio is being captured or transcribed — the app routes Esc
    /// to cancellation instead of its usual meaning.
    pub(crate) fn is_busy(&self) -> bool {
        matches!(
            self.state,
            VoiceState::Recording { .. } | VoiceState::Transcribing
        )
    }

    /// Does this key event start/stop dictation? `space` claims the keystroke
    /// only at a word boundary — the start of a line, or right after
    /// whitespace. Everywhere else a space is a separator being typed, and
    /// taking it would break the keyboard.
    ///
    /// The boundary rule needs no exception for a take already running: the
    /// provisional space this key just typed *is* the whitespace before the
    /// caret, so every repeat that follows still matches.
    pub(crate) fn matches_key(
        &self,
        code: crossterm::event::KeyCode,
        ctrl: bool,
        at_boundary: bool,
    ) -> bool {
        use crossterm::event::KeyCode;
        if !self.is_on() {
            return false;
        }
        match self.cfg.key {
            VoiceKey::CtrlSpace => ctrl && code == KeyCode::Char(' '),
            VoiceKey::Space => !ctrl && code == KeyCode::Char(' ') && at_boundary,
            VoiceKey::Function(n) => code == KeyCode::F(n),
        }
    }

    /// Does a take start out unsure of itself? Only when the key doubles as a
    /// character: everything else is unambiguous the moment it goes down.
    fn starts_provisional(&self) -> bool {
        self.cfg.key == VoiceKey::Space && self.end_detect != EndDetect::Toggle
    }

    /// Key releases carry whatever modifiers are *still* down, so a user who
    /// lets go of ctrl before space releases a bare space. Match the code only.
    pub(crate) fn matches_release(&self, code: crossterm::event::KeyCode) -> bool {
        use crossterm::event::KeyCode;
        if !self.is_on() {
            return false;
        }
        match self.cfg.key {
            VoiceKey::CtrlSpace | VoiceKey::Space => code == KeyCode::Char(' '),
            VoiceKey::Function(n) => code == KeyCode::F(n),
        }
    }

    /// Start the backend. A failure leaves voice *on* and unavailable, holding
    /// the reason, and hands that reason back for the caller to show properly:
    /// "your microphone is missing" deserves better than a notice that fades.
    pub(crate) fn turn_on(&mut self) -> Result<(), String> {
        // A backend already running is what makes starting a no-op — not being
        // "on", which also covers the states that come *before* one exists.
        // The install that just finished leaves voice in `Installing`, and
        // that is exactly the moment there is finally something to start.
        if self.backend.is_some() {
            return Ok(());
        }
        match (self.factory)(&self.cfg, self.events.clone()) {
            Ok(backend) => {
                self.backend = Some(backend);
                self.state = VoiceState::Warming(None);
                Ok(())
            }
            Err(reason) => {
                self.state = VoiceState::Unavailable(reason.clone());
                Err(reason)
            }
        }
    }

    /// Rebind for this session. Which key is free depends on the terminal and
    /// the input method, neither of which we can see, so trying one and
    /// keeping it has to be a two-second loop rather than a restart.
    pub(crate) fn set_key(&mut self, key: VoiceKey) {
        self.cfg.key = key;
        self.held = false;
    }

    /// Is there no sidecar on this machine yet? Asked before turning on, so
    /// the first use fetches one instead of reporting its absence.
    pub(crate) fn needs_install(&self) -> bool {
        sidecar::resolve(&self.cfg).is_err() && sidecar::release_asset().is_some()
    }

    /// Show the download before it starts, so `/voice on` has a visible effect
    /// even on a slow first byte.
    pub(crate) fn begin_install(&mut self) {
        self.state = VoiceState::Installing(0);
    }

    /// A sender for whoever is doing work on voice's behalf — currently the
    /// sidecar download, which reports on the same channel the sidecar will.
    pub(crate) fn events(&self) -> mpsc::Sender<VoiceEvent> {
        self.events.clone()
    }

    /// What the installed sidecar says it can run. Asked fresh each time the
    /// picker opens rather than cached: rebuilding the sidecar is exactly what
    /// changes the answer.
    pub(crate) fn catalogue(&self) -> Result<Vec<VoiceModel>, String> {
        list_models(&self.cfg)
    }

    /// The configured model name; empty means the sidecar's own default.
    pub(crate) fn model_name(&self) -> &str {
        &self.cfg.model
    }

    /// Point at a specific sidecar binary. Only tests use this, to keep the
    /// catalogue lookup off whatever is installed on the machine running them.
    #[cfg(test)]
    pub(crate) fn set_command(&mut self, command: String) {
        self.cfg.command = command;
    }

    /// Switch models. Unlike the key, this cannot be rebound in place: the
    /// sidecar loads its model once at startup, so the process is replaced.
    /// The name is not checked here — the sidecar owns the list, and it answers
    /// a wrong one with the menu.
    pub(crate) fn set_model(&mut self, name: String) -> Result<(), String> {
        self.cfg.model = name;
        self.restart()
    }

    /// The words recognition is biased towards.
    pub(crate) fn words(&self) -> &[String] {
        &self.cfg.hotwords
    }

    /// Replace the word list. Like the model, these are baked into the
    /// recogniser when it is built, so the sidecar is replaced.
    pub(crate) fn set_words(&mut self, words: Vec<String>) -> Result<(), String> {
        self.cfg.hotwords = words;
        self.restart()
    }

    /// Rebuild the backend around changed configuration, staying off if it was
    /// off — turning voice on is a separate decision from reconfiguring it.
    fn restart(&mut self) -> Result<(), String> {
        let was_on = self.is_on();
        self.turn_off();
        if was_on {
            self.turn_on()?;
        }
        Ok(())
    }

    /// Acknowledge a failure and clear the warning row, turning voice off —
    /// there is no working backend to stay on with. Returns whether there was
    /// anything to dismiss, so Esc keeps its usual meaning otherwise.
    pub(crate) fn dismiss_failure(&mut self) -> bool {
        if !matches!(self.state, VoiceState::Unavailable(_)) {
            return false;
        }
        self.turn_off();
        true
    }

    pub(crate) fn turn_off(&mut self) {
        // Dropping the backend closes the sidecar's stdin, which is how it is
        // asked to exit.
        self.backend = None;
        self.state = VoiceState::Off;
        self.held = false;
    }

    /// The key went down — or, while a take runs, it is still down.
    ///
    /// `auto_repeat` is the terminal saying so outright (`KeyEventKind::Repeat`,
    /// which only the richer input modes provide). Where it is available it
    /// settles the question on its own; where it is not, a *stream* of presses
    /// has to stand in for it, and one extra press is not a stream — that is
    /// just somebody typing two spaces.
    pub(crate) fn on_press(&mut self, auto_repeat: bool) -> VoiceOutcome {
        let was_held = self.held;
        self.held = true;
        match &self.state {
            VoiceState::Recording { .. } => match self.end_detect {
                // The one gesture where a second press means "stop".
                EndDetect::Toggle if !was_held => self.stop_take(),
                _ => {
                    self.press.note_repeat();
                    if !self.provisional {
                        return VoiceOutcome::None;
                    }
                    let machine_speed = self.press.gap.is_some_and(|gap| gap <= FAST_REPEAT);
                    if auto_repeat || (self.press.repeats >= PROVISIONAL_REPEATS && machine_speed) {
                        return self.confirm_hold();
                    }
                    // Still undecided, so this keystroke types too. Deciding
                    // late is free; swallowing a character is not.
                    self.provisional_chars += 1;
                    VoiceOutcome::TypeSpace
                }
            },
            VoiceState::Ready => {
                let outcome = self.begin();
                if !matches!(outcome, VoiceOutcome::None) {
                    return outcome;
                }
                // A key that is also a character types itself first and is
                // taken back only once the hold is proven. The alternative —
                // swallowing it — is what made `space` unusable for typing.
                if self.provisional {
                    self.provisional_chars = 1;
                    return VoiceOutcome::TypeSpace;
                }
                VoiceOutcome::None
            }
            VoiceState::Warming(_) => VoiceOutcome::Notice("voice is still starting up".into()),
            VoiceState::Unavailable(reason) => VoiceOutcome::Notice(reason.clone()),
            _ => VoiceOutcome::None,
        }
    }

    pub(crate) fn on_release(&mut self) -> VoiceOutcome {
        self.held = false;
        if !matches!(self.state, VoiceState::Recording { .. }) {
            return VoiceOutcome::None;
        }
        let VoiceState::Recording { since, .. } = self.state else {
            return VoiceOutcome::None;
        };
        match self.end_detect {
            // A real release is stronger evidence than capability probing. The
            // first one lets supported terminals stop future takes immediately.
            EndDetect::Repeat if since.elapsed() >= SYNTHETIC_RELEASE => {
                self.end_detect = EndDetect::Release;
                self.finish_real_release(since)
            }
            // Known to fabricate releases, or lacking a release signal. The
            // repeats decide until a real release proves otherwise.
            EndDetect::Repeat | EndDetect::Toggle => VoiceOutcome::None,
            EndDetect::Release if since.elapsed() >= SYNTHETIC_RELEASE => {
                self.finish_real_release(since)
            }
            // A release nobody's finger could have produced. The terminal is
            // manufacturing one per press, so key-up carries no information —
            // switch to watching auto-repeat and keep this take running. The
            // gesture does not change, so this needs no announcement.
            EndDetect::Release => {
                self.end_detect = EndDetect::Repeat;
                VoiceOutcome::Notice("voice: reading the hold from key repeat".into())
            }
        }
    }

    fn finish_real_release(&mut self, since: Instant) -> VoiceOutcome {
        if since.elapsed() < MIN_HOLD {
            let provisional = self.provisional;
            self.discard_take();
            // A tap on a key that is also a character is not a misfire at all
            // — the user typed a space, and it is already there.
            return if provisional {
                VoiceOutcome::None
            } else {
                VoiceOutcome::Notice("voice: hold the key while you speak".into())
            };
        }
        self.stop_take()
    }

    /// Esc while recording or transcribing throws the take away.
    pub(crate) fn cancel(&mut self) -> VoiceOutcome {
        if !self.is_busy() {
            return VoiceOutcome::None;
        }
        self.held = false;
        self.provisional = false;
        self.state = VoiceState::Ready;
        match self.send(VoiceCmd::Cancel) {
            Ok(()) => VoiceOutcome::Notice("voice cancelled".into()),
            Err(outcome) => outcome,
        }
    }

    pub(crate) fn is_recording(&self) -> bool {
        matches!(self.state, VoiceState::Recording { .. })
    }

    /// Runs while a take is open. Two jobs: cap a hold that never ends, and —
    /// when key-up is not to be trusted — notice that auto-repeat has stopped,
    /// which is how the finger coming off the key is observed at all.
    pub(crate) fn tick(&mut self) -> VoiceOutcome {
        let VoiceState::Recording { since, .. } = self.state else {
            return VoiceOutcome::None;
        };
        self.held = false;
        if since.elapsed() >= Duration::from_secs(self.cfg.max_seconds.max(1)) {
            return self.stop_take();
        }
        // Where a real key-up is trusted, a hold is proven by lasting: nothing
        // has to arrive, the release simply has not.
        if self.end_detect == EndDetect::Release {
            return if since.elapsed() >= MIN_HOLD {
                self.confirm_hold()
            } else {
                VoiceOutcome::None
            };
        }
        if self.end_detect != EndDetect::Repeat
            || self.press.last.elapsed() < self.press.idle_limit()
        {
            return VoiceOutcome::None;
        }
        // A take still provisional when the presses stop was never a hold we
        // could recognise, whatever it was. The characters it typed stay, and
        // it is emphatically not transcribed.
        if self.provisional {
            let enough_presses = self.press.repeats >= PROVISIONAL_REPEATS;
            self.discard_take();
            return if enough_presses {
                // The presses came, just too far apart to tell from typing.
                // That is this machine's key-repeat rate, which cannot be
                // fixed from in here — but a key that is not also a character
                // does not need telling apart at all.
                VoiceOutcome::Notice(
                    "voice: key repeat too slow to tell from typing — try /voice key f3".into(),
                )
            } else {
                VoiceOutcome::None
            };
        }
        if self.press.repeats > 0 {
            self.silent_takes = 0;
            return self.stop_take();
        }
        self.discard_take();
        // Otherwise it is either a misfire or a terminal that sends no repeat
        // either. One of those is recoverable and the other is not, so wait for
        // it to happen twice before giving up on the gesture.
        self.silent_takes += 1;
        if self.silent_takes < 2 {
            return VoiceOutcome::Notice("voice: hold the key while you speak".into());
        }
        self.end_detect = EndDetect::Toggle;
        VoiceOutcome::Announce(format!(
            "voice: this terminal reports neither a real key release nor key repeat, so there is \
             no way to tell how long the key is held — switched to {}.",
            self.gesture_help()
        ))
    }

    /// The take is real. Nothing to do unless it was provisional, in which
    /// case every character the key typed on the way in comes back out.
    fn confirm_hold(&mut self) -> VoiceOutcome {
        if !std::mem::take(&mut self.provisional) {
            return VoiceOutcome::None;
        }
        VoiceOutcome::RetractSpaces(std::mem::take(&mut self.provisional_chars))
    }

    pub(crate) fn on_event(&mut self, event: VoiceEvent) -> VoiceOutcome {
        match event {
            VoiceEvent::Ready => {
                if matches!(self.state, VoiceState::Warming(_)) {
                    self.state = VoiceState::Ready;
                }
                VoiceOutcome::None
            }
            VoiceEvent::Downloading(pct) => {
                self.state = VoiceState::Warming(Some(pct.min(100)));
                VoiceOutcome::None
            }
            VoiceEvent::Installing(pct) => {
                self.state = VoiceState::Installing(pct.min(100));
                VoiceOutcome::None
            }
            // The app starts the backend on this rather than routing it here:
            // there is no state for "installed", only "now it can run".
            VoiceEvent::Installed => VoiceOutcome::None,
            VoiceEvent::Level(rms) => {
                if let VoiceState::Recording { level, .. } = &mut self.state {
                    *level = rms.clamp(0.0, 1.0);
                }
                VoiceOutcome::None
            }
            VoiceEvent::Transcript(text) => {
                // A transcript that arrives after a cancel is not ours to
                // insert; the user already said they did not want it.
                if !matches!(self.state, VoiceState::Transcribing) {
                    return VoiceOutcome::None;
                }
                self.state = VoiceState::Ready;
                let text = text.trim().to_string();
                if text.is_empty() {
                    return VoiceOutcome::Notice("voice heard nothing".into());
                }
                VoiceOutcome::Insert(text)
            }
            VoiceEvent::Failed(message) => {
                self.state = VoiceState::Unavailable(message);
                self.held = false;
                // No notice: the hint row now holds the reason until it is
                // dismissed, and a fading notice would paint over the very line
                // that says how to dismiss it.
                VoiceOutcome::None
            }
        }
    }

    /// The hint row while voice is on. `None` means the normal status line.
    pub(crate) fn hint(&self) -> Option<VoiceHint> {
        let release = self.cfg.key.label();
        match &self.state {
            VoiceState::Off => None,
            // Named for what it is. "Downloading" alone would leave the user
            // wondering which of the two downloads this is, and they are very
            // different sizes.
            VoiceState::Installing(pct) => Some(VoiceHint {
                lead: "  ◌ voice".into(),
                rest: format!(" downloading the speech backend {pct}%"),
                tone: HintTone::Busy,
            }),
            VoiceState::Warming(None) => Some(VoiceHint {
                lead: "  ◌ voice".into(),
                rest: " starting up…".into(),
                tone: HintTone::Busy,
            }),
            VoiceState::Warming(Some(pct)) => Some(VoiceHint {
                lead: "  ◌ voice".into(),
                rest: format!(" downloading model {pct}% · esc cancels"),
                tone: HintTone::Busy,
            }),
            VoiceState::Ready => None,
            // A take still deciding whether it is one shows nothing: flashing
            // "recording" for half a second every time somebody types a space
            // would be worse than saying nothing at all.
            VoiceState::Recording { .. } if self.provisional => None,
            VoiceState::Recording { since, level } => {
                let secs = since.elapsed().as_secs();
                let stop = if self.end_detect == EndDetect::Toggle {
                    format!("{release} again")
                } else {
                    format!("release {release}")
                };
                Some(VoiceHint {
                    lead: format!("  ● {}:{:02} {}", secs / 60, secs % 60, meter(*level)),
                    rest: format!(" {stop} to transcribe · esc cancels"),
                    tone: HintTone::Recording,
                })
            }
            VoiceState::Transcribing => Some(VoiceHint {
                lead: "  ◌ transcribing…".into(),
                rest: " esc cancels".into(),
                tone: HintTone::Busy,
            }),
            // Says how to get rid of it. A warning with no stated exit is one
            // the user has to guess their way out of, and they will guess
            // "restart tcode".
            VoiceState::Unavailable(reason) => Some(VoiceHint {
                lead: "  ⚠ voice".into(),
                rest: format!(" {reason} · esc dismisses"),
                tone: HintTone::Problem,
            }),
        }
    }

    /// The marker in the idle status line. It names the key, not just the
    /// feature: "is it even listening, and to what" is precisely the question
    /// an armed-but-invisible mode leaves unanswered.
    pub(crate) fn status_marker(&self) -> Option<String> {
        match self.state {
            VoiceState::Off => None,
            VoiceState::Unavailable(_) => Some("voice ⚠".into()),
            _ => Some(format!("voice {}", self.cfg.key.label())),
        }
    }

    /// How to hold the key, for `/voice`'s confirmation line. Derived from the
    /// probe so the user never has to guess whether their terminal can do it.
    pub(crate) fn gesture_help(&self) -> String {
        let key = self.cfg.key.label();
        let empty = matches!(self.cfg.key, VoiceKey::Space)
            .then_some(" (with an empty prompt)")
            .unwrap_or_default();
        if self.end_detect == EndDetect::Toggle {
            format!("press {key}{empty} to start, press it again to transcribe")
        } else {
            format!("hold {key}{empty} to talk, release to transcribe")
        }
    }

    fn begin(&mut self) -> VoiceOutcome {
        match self.send(VoiceCmd::Start) {
            Ok(()) => {
                self.state = VoiceState::Recording {
                    since: Instant::now(),
                    level: 0.0,
                };
                self.press = PressTrack::new();
                self.provisional = self.starts_provisional();
                VoiceOutcome::None
            }
            Err(outcome) => outcome,
        }
    }

    /// End the take and transcribe it.
    fn stop_take(&mut self) -> VoiceOutcome {
        // Reaching here at all means the take was real, so any provisional
        // characters come back out before the transcript replaces them.
        let retract = self
            .provisional
            .then(|| std::mem::take(&mut self.provisional_chars));
        self.provisional = false;
        match self.send(VoiceCmd::Stop) {
            Ok(()) => {
                self.state = VoiceState::Transcribing;
                match retract {
                    Some(count) => VoiceOutcome::RetractSpaces(count),
                    None => VoiceOutcome::None,
                }
            }
            Err(outcome) => outcome,
        }
    }

    /// End the take and throw the audio away. Provisional characters stay:
    /// they were the user typing, which is what "no hold happened" means.
    fn discard_take(&mut self) {
        self.state = VoiceState::Ready;
        self.provisional = false;
        self.provisional_chars = 0;
        let _ = self.send(VoiceCmd::Cancel);
    }

    fn send(&mut self, cmd: VoiceCmd) -> Result<(), VoiceOutcome> {
        let Some(backend) = self.backend.as_mut() else {
            self.state = VoiceState::Unavailable("voice backend is gone".into());
            return Err(VoiceOutcome::Notice("voice backend is gone".into()));
        };
        backend.send(cmd).map_err(|reason| {
            self.state = VoiceState::Unavailable(reason.clone());
            VoiceOutcome::Notice(reason)
        })
    }
}

/// Five blocks of input level. Purely so a silent microphone is visibly
/// silent before the user finishes a sentence into a muted device.
fn meter(level: f32) -> String {
    const BARS: [char; 5] = ['▁', '▂', '▄', '▆', '█'];
    let filled = (level.clamp(0.0, 1.0) * BARS.len() as f32).round() as usize;
    (0..BARS.len())
        .map(|i| if i < filled { BARS[i] } else { '·' })
        .collect()
}

#[cfg(test)]
mod tests {
    use super::*;
    use std::sync::{Arc, Mutex};

    #[derive(Default)]
    struct FakeBackend {
        sent: Arc<Mutex<Vec<VoiceCmd>>>,
    }

    impl VoiceBackend for FakeBackend {
        fn send(&mut self, cmd: VoiceCmd) -> Result<(), String> {
            self.sent.lock().expect("lock").push(cmd);
            Ok(())
        }
    }

    fn voice() -> (Voice, Arc<Mutex<Vec<VoiceCmd>>>) {
        let sent = Arc::new(Mutex::new(Vec::new()));
        let handle = sent.clone();
        let (tx, _rx) = mpsc::channel(8);
        let factory: BackendFactory = Box::new(move |_, _| {
            Ok(Box::new(FakeBackend {
                sent: handle.clone(),
            }))
        });
        let mut voice = Voice::new(VoiceConfig::default(), tx, factory);
        voice.end_detect = EndDetect::Release;
        // A binding that is not also a character, so these tests are about the
        // take itself. The provisional path `space` takes has its own tests.
        voice.cfg.key = VoiceKey::CtrlSpace;
        (voice, sent)
    }

    /// The download ends in `Installing(100)`, which is "on" by every measure
    /// except the one that matters — there is no backend yet. Starting one
    /// then has to actually start it, or the finished download parks the hint
    /// row on "downloading 100%" forever and the key does nothing.
    #[test]
    fn a_finished_install_starts_the_backend_it_just_fetched() {
        let (mut voice, _sent) = voice();
        voice.begin_install();
        voice.on_event(VoiceEvent::Installing(100));

        voice.turn_on().expect("the fake backend starts");

        assert_eq!(voice.state, VoiceState::Warming(None));
        let hint = voice.hint().expect("starting up is worth showing");
        assert!(
            !hint.rest.contains("downloading"),
            "the hint row leaves the download behind: {}",
            hint.rest
        );
    }

    /// The whole point of the feature: audio in, editor text out, and the
    /// caller is the one that decides what to do with it.
    #[test]
    fn a_held_key_records_and_the_transcript_comes_back_as_text() {
        let (mut voice, sent) = voice();
        voice.turn_on().expect("the fake backend starts");
        voice.on_event(VoiceEvent::Ready);

        assert_eq!(voice.on_press(false), VoiceOutcome::None);
        assert!(matches!(voice.state, VoiceState::Recording { .. }));
        // Auto-repeat while the key is held must not restart the take.
        voice.on_press(false);
        assert_eq!(sent.lock().unwrap().as_slice(), &[VoiceCmd::Start]);

        voice.state = VoiceState::Recording {
            since: Instant::now() - Duration::from_secs(2),
            level: 0.4,
        };
        voice.on_release();
        assert_eq!(voice.state, VoiceState::Transcribing);

        let outcome = voice.on_event(VoiceEvent::Transcript("  改一下 editor  ".into()));
        assert_eq!(outcome, VoiceOutcome::Insert("改一下 editor".into()));
        assert_eq!(voice.state, VoiceState::Ready);
    }

    /// A cancelled take must stay cancelled even if the sidecar was already
    /// far enough along to answer.
    #[test]
    fn a_transcript_arriving_after_cancel_is_dropped() {
        let (mut voice, _sent) = voice();
        voice.turn_on().expect("the fake backend starts");
        voice.on_event(VoiceEvent::Ready);
        voice.state = VoiceState::Transcribing;

        voice.cancel();
        assert_eq!(voice.state, VoiceState::Ready);
        assert_eq!(
            voice.on_event(VoiceEvent::Transcript("late".into())),
            VoiceOutcome::None
        );
    }

    #[test]
    fn a_hold_past_the_cap_stops_itself() {
        let (mut voice, sent) = voice();
        voice.turn_on().expect("the fake backend starts");
        voice.on_event(VoiceEvent::Ready);
        voice.on_press(false);
        voice.state = VoiceState::Recording {
            since: Instant::now() - Duration::from_secs(61),
            level: 0.0,
        };

        voice.tick();
        assert_eq!(voice.state, VoiceState::Transcribing);
        assert_eq!(
            sent.lock().unwrap().as_slice(),
            &[VoiceCmd::Start, VoiceCmd::Stop]
        );
    }

    #[test]
    fn a_real_release_promotes_repeat_detection() {
        let (mut voice, sent) = voice();
        voice.turn_on().expect("the fake backend starts");
        voice.on_event(VoiceEvent::Ready);
        voice.set_end_detect(EndDetect::Repeat);

        voice.on_press(false);
        voice.pretend_recording_started(Duration::from_millis(250));
        assert_eq!(voice.on_release(), VoiceOutcome::None);
        assert_eq!(voice.end_detect, EndDetect::Release);
        assert_eq!(voice.state, VoiceState::Transcribing);
        assert_eq!(
            sent.lock().unwrap().as_slice(),
            &[VoiceCmd::Start, VoiceCmd::Stop]
        );
    }

    /// The failure this feature actually hit, and the fix for it: under a
    /// pseudoconsole the release is fabricated in the same instant as the
    /// press, so key-up says nothing — but auto-repeat still arrives, and the
    /// gap after the last repeat is the finger coming off the key. The gesture
    /// stays hold-to-talk; only how its end is observed changes.
    #[test]
    fn a_fabricated_release_falls_back_to_reading_the_hold_from_key_repeat() {
        let (mut voice, sent) = voice();
        voice.turn_on().expect("the fake backend starts");
        voice.on_event(VoiceEvent::Ready);

        voice.on_press(false);
        let outcome = voice.on_release();

        assert!(matches!(outcome, VoiceOutcome::Notice(_)));
        assert_eq!(voice.end_detect, EndDetect::Repeat);
        assert!(
            matches!(voice.state, VoiceState::Recording { .. }),
            "the take survives — the microphone is still open"
        );
        assert!(
            voice.gesture_help().contains("hold"),
            "still hold-to-talk: {}",
            voice.gesture_help()
        );

        // The key is still down, so repeats keep arriving. Each one is
        // evidence, never a second gesture.
        for _ in 0..5 {
            voice.on_press(false);
            voice.on_release();
        }
        assert!(matches!(voice.state, VoiceState::Recording { .. }));
        assert_eq!(sent.lock().unwrap().as_slice(), &[VoiceCmd::Start]);

        // Finger up: the repeats stop, and the next tick past the gap ends it.
        voice.pretend_recording_started(Duration::from_secs(2));
        voice.press.last = Instant::now() - Duration::from_secs(1);
        voice.tick();

        assert_eq!(voice.state, VoiceState::Transcribing);
        assert_eq!(
            sent.lock().unwrap().as_slice(),
            &[VoiceCmd::Start, VoiceCmd::Stop]
        );
    }

    /// The gap that means "released" has to clear the machine's own repeat
    /// rate, or a slow repeat setting would chop every take into fragments.
    #[test]
    fn the_release_gap_adapts_to_the_observed_repeat_rate() {
        let mut press = PressTrack::new();
        assert_eq!(
            press.idle_limit(),
            REPEAT_START,
            "before any repeat, wait out the OS repeat delay"
        );

        // The first gap is the repeat *delay*, which must not be mistaken for
        // the rate.
        press.note_repeat();
        assert_eq!(press.idle_limit(), REPEAT_START);

        press.last = Instant::now() - Duration::from_millis(200);
        press.note_repeat();
        assert!(
            press.idle_limit() >= Duration::from_millis(600),
            "a 200ms repeat interval needs more than 200ms of silence to call it released"
        );
    }

    /// A real finger is slower than `SYNTHETIC_RELEASE`, so a genuine misfire
    /// is still just a misfire and must not rewrite how takes end.
    #[test]
    fn a_real_but_short_tap_is_discarded_without_changing_the_gesture() {
        let (mut voice, _sent) = voice();
        voice.turn_on().expect("the fake backend starts");
        voice.on_event(VoiceEvent::Ready);

        voice.on_press(false);
        voice.pretend_recording_started(Duration::from_millis(120));
        let outcome = voice.on_release();

        assert!(matches!(outcome, VoiceOutcome::Notice(_)));
        assert_eq!(voice.state, VoiceState::Ready);
        assert_eq!(voice.end_detect, EndDetect::Release);
    }

    /// Last resort: no usable release *and* no repeat. Give up on the hold
    /// only after it has failed twice, and say so where it can be re-read.
    #[test]
    fn a_terminal_with_neither_signal_becomes_a_toggle_after_two_takes() {
        let (mut voice, _sent) = voice();
        voice.turn_on().expect("the fake backend starts");
        voice.on_event(VoiceEvent::Ready);
        voice.set_end_detect(EndDetect::Repeat);

        for _ in 0..2 {
            voice.on_press(false);
            voice.press.last = Instant::now() - REPEAT_START - Duration::from_millis(10);
            voice.tick();
        }

        assert_eq!(voice.end_detect, EndDetect::Toggle);
        assert!(voice.gesture_help().contains("again"));

        // And from here the same key starts and stops.
        voice.on_press(false);
        assert!(matches!(voice.state, VoiceState::Recording { .. }));
        voice.pretend_recording_started(Duration::from_secs(2));
        voice.on_release();
        assert!(
            matches!(voice.state, VoiceState::Recording { .. }),
            "a release means nothing here"
        );
        voice.held = false;
        voice.on_press(false);
        assert_eq!(voice.state, VoiceState::Transcribing);
    }

    /// A function key is the escape hatch for a chord something else has
    /// claimed, so it must work with a full draft and with no modifiers rules
    /// attached.
    #[test]
    fn a_function_key_binding_matches_regardless_of_the_draft() {
        use crossterm::event::KeyCode;
        let (mut voice, _sent) = voice();
        voice.turn_on().expect("the fake backend starts");
        voice.set_key(VoiceKey::Function(4));

        assert!(voice.matches_key(KeyCode::F(4), false, false));
        assert!(voice.matches_key(KeyCode::F(4), false, true));
        assert!(voice.matches_release(KeyCode::F(4)));
        assert!(!voice.matches_key(KeyCode::F(5), false, true));
        // Space is back to being a character once the binding moved.
        assert!(!voice.matches_key(KeyCode::Char(' '), true, true));
        assert!(!voice.matches_release(KeyCode::Char(' ')));
    }

    /// Binding `space` must not cost the user the space bar. A tap types a
    /// space like always; only a proven hold takes it back and becomes a take.
    #[test]
    fn a_tapped_space_stays_typed_and_a_held_one_is_taken_back() {
        let (mut voice, sent) = voice();
        voice.cfg.key = VoiceKey::Space;
        voice.turn_on().expect("the fake backend starts");
        voice.on_event(VoiceEvent::Ready);
        voice.set_end_detect(EndDetect::Repeat);

        // Tap: the character is typed, and nothing on screen says "recording".
        assert_eq!(voice.on_press(false), VoiceOutcome::TypeSpace);
        assert!(voice.hint().is_none(), "no recording row while unsure");
        voice.on_release();
        voice.press.last = Instant::now() - REPEAT_START - Duration::from_millis(10);
        assert_eq!(
            voice.tick(),
            VoiceOutcome::None,
            "a typed space is not news"
        );
        assert_eq!(voice.state, VoiceState::Ready);
        assert_eq!(
            sent.lock().unwrap().as_slice(),
            &[VoiceCmd::Start, VoiceCmd::Cancel]
        );

        // Typing a second space is not a hold, and must not become one.
        assert_eq!(voice.on_press(false), VoiceOutcome::TypeSpace);
        assert_eq!(
            voice.on_press(false),
            VoiceOutcome::TypeSpace,
            "one extra press is what typing two spaces looks like"
        );
        assert!(voice.hint().is_none(), "still not recording");

        // A held key repeats faster than that. The press that settles it does
        // not type, and every character the earlier ones let through comes
        // back out at once.
        assert_eq!(
            voice.on_press(false),
            VoiceOutcome::RetractSpaces(2),
            "both provisional spaces, not just the first"
        );
        assert!(voice.hint().is_some(), "now it is a real take");
        // The repeats that prove the hold still reach voice, and need no
        // exception to do it: the provisional space this key typed is itself
        // the whitespace that puts the caret on a word boundary.
        assert!(voice.matches_key(crossterm::event::KeyCode::Char(' '), false, true));
        assert_eq!(
            voice.on_press(false),
            VoiceOutcome::None,
            "retracted only once"
        );
    }

    /// A terminal that labels auto-repeat settles it on the first one — no
    /// counting, no flurry of characters to take back.
    #[test]
    fn a_labelled_auto_repeat_confirms_the_hold_immediately() {
        let (mut voice, _sent) = voice();
        voice.cfg.key = VoiceKey::Space;
        voice.turn_on().expect("the fake backend starts");
        voice.on_event(VoiceEvent::Ready);
        voice.set_end_detect(EndDetect::Repeat);

        assert_eq!(voice.on_press(false), VoiceOutcome::TypeSpace);
        assert_eq!(voice.on_press(true), VoiceOutcome::RetractSpaces(1));
    }

    /// Presses far enough apart to be typing never become a take, however many
    /// of them arrive — and the user is told why, since it is a machine
    /// setting they would otherwise have to guess at.
    #[test]
    fn presses_at_human_speed_stay_typed_however_many_there_are() {
        let (mut voice, _sent) = voice();
        voice.cfg.key = VoiceKey::Space;
        voice.turn_on().expect("the fake backend starts");
        voice.on_event(VoiceEvent::Ready);
        voice.set_end_detect(EndDetect::Repeat);

        assert_eq!(voice.on_press(false), VoiceOutcome::TypeSpace);
        for _ in 0..4 {
            // Slower than any key repeats, i.e. somebody typing.
            voice.press.last = Instant::now() - Duration::from_millis(300);
            assert_eq!(voice.on_press(false), VoiceOutcome::TypeSpace);
        }
        assert!(voice.hint().is_none(), "never a take");

        voice.press.last = Instant::now() - Duration::from_secs(2);
        let outcome = voice.tick();
        assert!(
            matches!(&outcome, VoiceOutcome::Notice(text) if text.contains("/voice key")),
            "points at the binding that does not need telling apart: {outcome:?}"
        );
        assert_eq!(voice.state, VoiceState::Ready);
    }

    #[test]
    fn space_is_only_a_gesture_while_the_draft_is_empty() {
        use crossterm::event::KeyCode;
        let (mut voice, _sent) = voice();
        voice.cfg.key = VoiceKey::Space;
        voice.turn_on().expect("the fake backend starts");

        assert!(voice.matches_key(KeyCode::Char(' '), false, true));
        assert!(!voice.matches_key(KeyCode::Char(' '), false, false));
        // ctrl+space is the other binding's gesture, not this one's.
        assert!(!voice.matches_key(KeyCode::Char(' '), true, true));
    }

    #[test]
    fn a_backend_failure_is_shown_rather_than_silently_turning_voice_off() {
        let (tx, _rx) = mpsc::channel(8);
        let factory: BackendFactory = Box::new(|_, _| Err("no input device".into()));
        let mut voice = Voice::new(VoiceConfig::default(), tx, factory);

        assert_eq!(voice.turn_on(), Err("no input device".into()));
        assert!(voice.is_on(), "still on, just unusable");
        assert!(voice
            .hint()
            .is_some_and(|hint| hint.tone == HintTone::Problem));
    }
}
